export const cases: [string, string, string][] = [
 ['empty list factory', 'println(emptyList<Int>().fold(7) { a, b -> a + b })', '7'],
 ['declared class filter', 'class Item(val n: Int)\nprintln(listOf(Item(4), "x").filterIsInstance<Item>().map { it.n })', '[4]'],
 ['partition destructuring', 'val (yes, no) = listOf(1, 2, 3).partition { it > 1 }\nprintln(yes)\nprintln(no)', '[2, 3]\n[1]'],
 ['group map lookup', 'val groups = listOf(1, 2, 3).groupBy { it % 2 }\nprintln(groups[1])', '[1, 3]'],
 ['boolean filter', 'println(listOf(1, true, false).filterIsInstance<Boolean>())', '[true, false]'],
 ['map/filter chain', 'println(listOf(1, 2, 3).filter { it > 1 }.map { it * 2 }.first())', '4'],
 ['mapNotNull', 'println(listOf(1, 2, 3).mapNotNull { if (it > 1) it else null })', '[2, 3]'],
 ['filterNot', 'println(listOf(1, 2, 3).filterNot { it == 2 })', '[1, 3]'],
 ['type filter', 'println(listOf(1, "two", true).filterIsInstance<String>())', '[two]'],
 ['number filter', 'println(listOf(1, "two", 2.5).filterIsInstance<Number>())', '[1, 2.5]'],
 ['flatMap iterable', 'println(listOf(1, 2).flatMap { setOf(it, it + 10) })', '[1, 11, 2, 12]'],
 ['flatten/fold', 'println(listOf(listOf(1, 2), listOf(3)).flatten().fold(10) { a, b -> a + b })', '16'],
 ['reduce', 'println(listOf(2, 3, 4).reduce { a, b -> a * b })', '24'],
 ['empty fold', 'println(listOf<Int>().fold(10) { a, b -> a + b })', '10'],
 ['groupBy', 'println(listOf(1, 2, 3).groupBy { it % 2 })', '{1=[1, 3], 0=[2]}'],
 ['associate pair', 'println(listOf(1, 2, 3).associate { it % 2 to it })', '{1=3, 0=2}'],
 ['partition single pass', 'var calls = 0\nval split = listOf(1, 2, 3).partition { calls++; it > 1 }\nprintln(split.first)\nprintln(split.second)\nprintln(calls)', '[2, 3]\n[1]\n3'],
 ['zip pairs', 'println(listOf(1, 2, 3).zip(listOf("a", "b")))', '[(1, a), (2, b)]'],
 ['zip transform', 'println(listOf(1, 2).zip(listOf(10, 20)) { a, b -> a + b })', '[11, 22]'],
 ['chunk transform', 'println(listOf(1, 2, 3).chunked(2) { it.sum() })', '[3, 3]'],
 ['window default', 'println(listOf(1, 2, 3, 4).windowed(3))', '[[1, 2, 3], [2, 3, 4]]'],
 ['window named', 'println(listOf(1, 2, 3, 4, 5).windowed(3, partialWindows = true, step = 2) { it.sum() })', '[6, 12, 5]'],
 ['distinct nested', 'println(listOf(listOf(1), listOf(1), listOf(2)).distinct())', '[[1], [2]]'],
 ['sorted strings', 'println(listOf("z", "a", "b").sorted())\nprintln(listOf("z", "a").minOrNull())', '[a, b, z]\na'],
 ['sorted selector', 'println(listOf("aa", "b", "cc").sortedBy { it.length })', '[b, aa, cc]'],
 ['extrema', 'println(listOf(5, 2, 8).min())\nprintln(listOf(5, 2, 8).max())\nprintln(listOf<Int>().maxOrNull())', '2\n8\nnull'],
 ['sum average', 'println(listOf(1, 2, 3).sum())\nprintln(listOf(1, 2).average())\nprintln(listOf<Int>().average())', '6\n1.5\nNaN'],
 ['empty predicates', 'println(listOf<Int>().any())\nprintln(listOf<Int>().all { it > 0 })\nprintln(listOf<Int>().none())', 'false\ntrue\ntrue'],
 ['first predicate', 'println(listOf(1, 2, 3).first { it > 1 })\nprintln(listOf(1).find { it > 2 })\nprintln(listOf<Int>().firstOrNull())', '2\nnull\nnull'],
 ['count chain', 'println(listOf(1, 2, 3).map { it * 2 }.count { it > 2 })', '2'],
 ['no mutation', 'val values = listOf(3, 1, 2)\nprintln(values.sorted())\nprintln(values)', '[1, 2, 3]\n[3, 1, 2]'],
];
