/**
 * Writes src/data/stageLessonKeys.ts: for every lesson-registry key that is not the lesson's own id (short aliases like "kotlin-syntax",
 * truncated keys, "world-12-boss"), which lesson id it means. The stage (data/stageLessonSource.ts) loads one World's data on its own
 * and needs this to turn the key the app passes into the lesson, without importing the all-World registry.
 *
 *   npm run generate:stage-keys           write the file
 *   npm run generate:stage-keys -- --check  exit 1 if it is out of date
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { AVAILABLE_FIVE_STAGE_LESSONS } from '../src/data/lessonStagesData';

const here = path.dirname(fileURLToPath(import.meta.url));
const file = path.resolve(here, '../src/data/stageLessonKeys.ts');

const aliases: Record<string, string> = {};
for (const key of Object.keys(AVAILABLE_FIVE_STAGE_LESSONS).sort()) {
  const lesson = AVAILABLE_FIVE_STAGE_LESSONS[key];
  if (key !== lesson.id) aliases[key] = lesson.id;
}

const text = `// GENERATED by scripts/generate-stage-lesson-keys.ts (npm run generate:stage-keys). Do not edit by hand.
// Lesson-registry keys that differ from the lesson's own id, and the id they mean. Used by data/stageLessonSource.ts.
export const STAGE_LESSON_KEY_TO_ID: Record<string, string> = ${JSON.stringify(aliases, null, 2)};
`;

if (process.argv.includes('--check')) {
  const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
  if (current !== text) {
    console.error('src/data/stageLessonKeys.ts is out of date. Run: npm run generate:stage-keys (in web-editor/)');
    process.exit(1);
  }
  console.log(`Stage lesson keys are up to date (${Object.keys(aliases).length} aliases).`);
} else {
  fs.writeFileSync(file, text);
  console.log(`wrote src/data/stageLessonKeys.ts (${Object.keys(aliases).length} aliases)`);
}
