/**
 * Regenerates the data files the React Native native screens read (../src/*.ts marked "GENERATED") from this
 * project's lesson data, so the native screens and the web editor never drift apart.
 *
 *   npm run generate:native-data           write the files
 *   npm run generate:native-data -- --check  fail (exit 1) if any file differs from what would be written
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { CODEDO_MASTER_WORLDS } from '../src/data/curriculum/masterCurriculumCatalog';
import { PRACTICE_WRITE_RUN_BANK, PRACTICE_DEBUG_BANK } from '../src/data/practiceBank';
import { AVAILABLE_FIVE_STAGE_LESSONS } from '../src/data/lessonStagesData';
import { WORLD_1_QUIZ } from '../src/data/quizBank/world1Quiz';

const here = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(here, '../../src');
const json = (v: unknown) => JSON.stringify(v, null, 1);

// Same rule as WriteRun.tsx's extractGivenLines (kept in sync by hand: that file imports React/DOM modules).
const extractGivenLines = (initialCode: string): string[] => {
  const lines = (initialCode || '').replace(/\r\n/g, '\n').split('\n');
  if (lines.some((l) => /^\s*fun\s+(?!main\b)/.test(l))) return [];
  const mainIdx = lines.findIndex((l) => /^\s*fun\s+main\s*\(/.test(l));
  const body = lines.slice(mainIdx + 1);
  const stepIdx = body.findIndex((l) => /^\s*\/\/\s*\d+\./.test(l));
  const given = (stepIdx === -1 ? [] : body.slice(0, stepIdx)).filter((l) => l.trim() !== '' && !/^\s*\/\//.test(l));
  const indent = Math.min(...given.map((l) => l.match(/^\s*/)![0].length), Infinity);
  return Number.isFinite(indent) ? given.map((l) => l.slice(indent)) : [];
};

const files: Record<string, string> = {};

// ---- curriculumData.ts
{
  const header = `// GENERATED by web-editor/scripts/generate-native-data.ts from web-editor/src/data/curriculum/masterCurriculumCatalog.ts: every World's title, subtitle, lesson titles and boss challenge, as the web
// Curriculum screen shows them. UI only. Do not edit by hand.
export interface CurriculumWorld {
  order: number;
  title: string;
  subtitle: string;
  lessonCount: number;
  available: boolean;
  lessons: string[];
  boss: string | null;
}

export const CURRICULUM_WORLDS: CurriculumWorld[] = `;
  const worlds = CODEDO_MASTER_WORLDS.map((w) => ({
    order: w.order,
    title: w.title,
    subtitle: w.subtitle,
    lessonCount: w.lessons.length,
    available: w.lessons.some((l) => !!l.fiveStageLessonKey),
    lessons: w.lessons.filter((l) => l.skill !== 'boss').map((l) => l.title),
    boss: w.bossTitle || null,
  }));
  files['curriculumData.ts'] = header + json(worlds) + ';\n';
}

// ---- practiceTasks.ts
{
  const header = `// GENERATED by web-editor/scripts/generate-native-data.ts from web-editor/src/data/practiceBank (Worlds 1-8): the titles, summaries, goals, starting values and expected outputs the web task list shows.
// Do not edit by hand. UI only: statuses are made up in TaskListScreen.tsx.
export interface PracticeTask {
  title: string;
  summary: string;
  difficulty: 'easy' | 'medium' | 'hard';
  goal?: string;
  bug?: string;
  given: string[];
  expected: string;
}

export const PRACTICE_TASKS: Record<number, { writeRun: PracticeTask[]; debug: PracticeTask[] }> = `;
  const out: Record<string, { writeRun: unknown[]; debug: unknown[] }> = {};
  const worldIds = Object.keys(PRACTICE_WRITE_RUN_BANK);
  for (const id of worldIds) {
    const n = id.replace('world-', '');
    out[n] = {
      writeRun: PRACTICE_WRITE_RUN_BANK[id].map((p) => ({
        title: p.title,
        summary: p.summary ?? '',
        difficulty: p.difficulty,
        goal: p.goal,
        given: extractGivenLines(p.initialCode),
        expected: p.expectedOutput,
      })),
      debug: (PRACTICE_DEBUG_BANK[id] ?? []).map((p) => ({
        title: p.title,
        summary: p.summary ?? '',
        difficulty: p.difficulty,
        bug: p.subtitle,
        given: [],
        expected: p.expectedOutput,
      })),
    };
  }
  files['practiceTasks.ts'] = header + json(out) + ';\n';
}

// ---- lessonData.ts
{
  const header = `// GENERATED by web-editor/scripts/generate-native-data.ts from the web lesson data (lessonStagesData + masterCurriculumCatalog): the Learn, Explore, Predict and Mastered content of every lesson,
// keyed "worldOrder:lessonTitle" (the title the Curriculum list shows). Write & Run and Debug are not included here: they run in the web editor (web-editor/). Do not edit by hand.
export interface LessonData {
  id: string; key: string; worldName: string; topicTitle: string;
  learn: { title: string; subtitle: string; exampleTitle: string; codeSnippet: string[]; explanation: string; keyIdeas: { number: number; title: string; description: string }[]; keyTakeaway: string };
  explore?: { title: string; subtitle: string; cards: { id: string; number: string; title: string; language: string; subtitle: string; code: string[]; whatItMeans: { label: string; description: string }[]; whatChanged: string }[] };
  predict?: { title: string; subtitle?: string; questions: { id: string; topicMeta: string; title?: string; language: string; code?: string[]; prompt: string; options: { id: string; label: string; isCorrect: boolean }[]; explanation: { codeRef: string; detail: string } }[] };
  mastered: { topicTitle: string; summary: string; passedCount: string; verificationItems: { title: string; subtitle: string }[]; xpEarned: number; streakDays: number; accuracy: string };
  hasWriteRun: boolean; hasDebug: boolean; boss: boolean;
}
export const LESSONS: Record<string, LessonData> = `;
  const lessons: Record<string, unknown> = {};
  for (const w of CODEDO_MASTER_WORLDS) {
    for (const l of w.lessons) {
      const f = l.fiveStageLessonKey ? AVAILABLE_FIVE_STAGE_LESSONS[l.fiveStageLessonKey] : undefined;
      if (!f) continue;
      lessons[`${w.order}:${l.title}`] = {
        id: f.id,
        key: l.fiveStageLessonKey,
        worldName: f.worldName,
        topicTitle: f.topicTitle,
        learn: f.learn,
        explore: f.explore,
        predict: f.predict,
        mastered: f.mastered,
        hasWriteRun: !!f.writeRun,
        hasDebug: !!f.debug,
        boss: l.skill === 'boss',
      };
    }
  }
  files['lessonData.ts'] = header + JSON.stringify(lessons) + ' as unknown as Record<string, LessonData>;\n';
}

// ---- quizSample.ts
{
  // A hand-picked 12-question sample session (these ids, in this order) from the World 1 quiz bank.
  const SAMPLE_IDS = [
    'w1q-what-1', 'w1q-syntax-1', 'w1q-syntax-3', 'w1q-comments-1', 'w1q-comments-2', 'w1q-print-1',
    'w1q-valvar-1', 'w1q-valvar-3', 'w1q-char-2', 'w1q-template-1', 'w1q-print-3', 'w1q-valvar-4',
  ];
  const header = `// GENERATED by web-editor/scripts/generate-native-data.ts from web-editor/src/data/quizBank/world1Quiz.ts: a 12-question sample session for the React Native Quiz.
// Only World 1 has a quiz bank in the new question format, so every World card plays this sample for now. UI only. Do not edit by hand.
import { QuizQuestion } from './quizQuestions';

export const SAMPLE_QUIZ: QuizQuestion[] = `;
  const questions = SAMPLE_IDS.map((id) => {
    const q = WORLD_1_QUIZ.find((x) => x.id === id);
    if (!q) throw new Error(`quizSample: question ${id} is no longer in WORLD_1_QUIZ`);
    return q;
  });
  files['quizSample.ts'] = header + json(questions) + ';\n';
}

// ---- world1Quiz.ts (the quiz bank itself: web-editor/src/data/quizBank/world1Quiz.ts is the only place it is edited)
{
  const source = fs.readFileSync(path.resolve(here, '../src/data/quizBank/world1Quiz.ts'), 'utf8');
  const importLine = "import { QuizQuestion } from '../../utils/quizQuestions';";
  if (!source.includes(importLine)) throw new Error('world1Quiz.ts: expected import line not found; update generate-native-data.ts');
  files['world1Quiz.ts'] =
    '// GENERATED by web-editor/scripts/generate-native-data.ts from web-editor/src/data/quizBank/world1Quiz.ts. Do not edit by hand.\n' +
    source.replace(importLine, "import { QuizQuestion } from './quizQuestions';");
}

const check = process.argv.includes('--check');
let bad = 0;
for (const [name, text] of Object.entries(files)) {
  const file = path.join(OUT, name);
  const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
  if (check) {
    if (current !== text) {
      bad++;
      console.error(`DIFFERS: src/${name}`);
    }
  } else if (current !== text) {
    fs.writeFileSync(file, text);
    console.log(`wrote src/${name}`);
  }
}
if (check) {
  if (bad) {
    console.error(`\n${bad} generated file(s) are out of date. Run: npm run generate:native-data (in web-editor/)`);
    process.exit(1);
  }
  console.log(`Native data is up to date (${Object.keys(files).length} files).`);
}
