export const nullSafetyCases: Array<{ name: string; body: string; output: string; error?: 'compiler_error' | 'runtime_error'; message?: string }> = [
 { name: 'two independent assertions', body: 'val a: Int? = 2\nval b: Int? = 3\nprintln(a!! + b!!)', output: '5' },
 { name: 'second assertion fails', body: 'val a: Int? = 2\nval b: Int? = null\nprintln(a!! + b!!)', output: '', error: 'runtime_error', message: 'NullPointerException' },
 { name: 'quoted map assertion', body: 'val m = mapOf("a" to 4)\nprintln(m["a"]!!)', output: '4' },
 { name: 'function assertion', body: 'fun value(): String? = "ok"\nprintln(value()!!.length)', output: '2' },
 { name: 'chained assertions', body: 'class Box(val name: String?)\nval box: Box? = Box("ok")\nprintln(box!!.name!!.length)', output: '2' },
 { name: 'left associative assertion arithmetic', body: 'val a: Int? = 10\nval b: Int? = 3\nval c: Int? = 2\nprintln(a!! - b!! - c!!)', output: '5' },
 { name: 'integer division after assertion', body: 'val a: Int? = 7\nprintln(a!! / 2)', output: '3' },
 { name: 'Char check unsupported', body: 'val a: Any = "x"\nprintln(a is Char)', output: '', error: 'compiler_error', message: 'not simulated' },
 { name: 'Char negated check unsupported', body: 'val a: Any = "x"\nprintln(a !is Char)', output: '', error: 'compiler_error', message: 'not simulated' },
 { name: 'Char cast unsupported', body: 'val a: Any = "x"\nprintln(a as? Char)', output: '', error: 'compiler_error', message: 'not simulated' },
 { name: 'Char source is not String', body: "val a: Any = 'x'\nprintln(a as? String)", output: '', error: 'compiler_error', message: 'not simulated' },
 { name: 'no numeric cast coercion', body: 'val a: Any = 2.5\nprintln(a as? Int)', output: 'null' },
 { name: 'mutable numeric runtime type rejected', body: 'var a: Any = 2\na = 2.5\nprintln(a as? Int)', output: '', error: 'compiler_error', message: 'mutable sources' },
 { name: 'unrepresented numeric type rejected', body: 'fun cast(a: Any) {\nprintln(a as? Int)\n}\ncast(2.5)', output: '', error: 'compiler_error', message: 'known primitive source type' },
 { name: 'multiple generic parameters', body: 'val m: Map<String, Int?> = mapOf("a" to 4, "b" to null)\nprintln(m["a"])\nprintln(m["b"])', output: '4\nnull' },
 { name: 'nested nullable generics', body: 'val m: Map<String, List<Int?>?>? = mapOf("a" to listOf(1, null))\nprintln(m?.get("a")?.size)', output: '2' },
 { name: 'all null output contexts', body: 'val name: String? = null\nval size = name?.length\nprintln(size)\nprintln("size=$size")\nprintln("size=" + size)\nprintln("size=${name?.length}")\nprintln("size=" + name?.length)', output: 'null\nsize=null\nsize=null\nsize=null\nsize=null' },
 { name: 'nullable arithmetic rejected', body: 'val n: Int? = null\nprintln(n + 1)', output: '', error: 'compiler_error', message: 'before arithmetic' },
 { name: 'unguarded null access rejected', body: 'val name: String? = null\nprintln(name.length)', output: '', error: 'compiler_error', message: 'nullable receiver' },
 { name: 'Elvis boolean precedence', body: 'val enabled: Boolean? = false\nprintln(enabled ?: true || true)', output: 'true' },
 { name: 'Elvis comparison precedence', body: 'val n: Int? = 2\nprintln(n ?: 0 > 1)', output: 'true' },
 { name: 'safe cast once', body: 'var count = 0\nfun next(): Any {\ncount += 1\nreturn "x"\n}\nprintln(next() as? String)\nprintln(count)', output: 'x\n1' },
 { name: 'safe method on function result', body: 'fun names(): List<String>? = listOf("a", "b")\nprintln(names()?.size)', output: '2' },
 { name: 'multiple statements per line', body: 'val a: Int? = 2; val b: Int? = 3; println(a!!); println(b!!)', output: '2\n3' },
];
