// GENERATED by scripts/generate-stage-lesson-keys.ts (npm run generate:stage-keys). Do not edit by hand.
// Lesson-registry keys that differ from the lesson's own id, and the id they mean. Used by data/stageLessonSource.ts.
export const STAGE_LESSON_KEY_TO_ID: Record<string, string> = {
  "arithmetic-operators": "world-2-arithmetic-operators",
  "assignment-operators": "world-2-assignment-operators",
  "boolean": "world-1-boolean",
  "char": "world-1-char",
  "comments": "world-1-comments",
  "comparison-operators": "world-2-comparison-operators",
  "float-double": "world-1-float-double",
  "increment-decrement": "world-2-increment-decrement",
  "int-long": "world-1-int-long",
  "kotlin-syntax": "world-1-kotlin-syntax",
  "logical-operators": "world-2-logical-operators",
  "operator-precedence": "world-2-operator-precedence",
  "print-println": "world-1-print-println",
  "string": "world-1-string",
  "string-templates": "world-1-string-templates",
  "val-vs-var": "world-1-val-vs-var",
  "variables-type-inference": "world-1-variables-type-inference",
  "what-is-kotlin": "world-1-what-is-kotlin",
  "world-11-data-classes-in-domain-modeling-enum-cla": "world-11-data-classes-in-domain-modeling-enum-classes",
  "world-11-interfaces-multiple-interface-implementa": "world-11-interfaces-multiple-interface-implementation",
  "world-12-boss": "world-12-generic-data-toolkit-boss"
};
