// GENERATED by web-editor/scripts/generate-native-data.ts: totals of the lessons (five stages), the Quiz tab and the Practice tab. Do not edit by hand.
export const CONTENT_STATS = {
 "worlds": 22,
 "lessons": 273,
 "stages": {
  "learn": {
   "lessons": 196,
   "items": 196
  },
  "explore": {
   "lessons": 195,
   "items": 988
  },
  "predict": {
   "lessons": 196,
   "items": 1004
  },
  "writeRun": {
   "lessons": 191,
   "items": 191
  },
  "debug": {
   "lessons": 192,
   "items": 192
  }
 },
 "quizQuestions": 147,
 "practice": {
  "writeRun": 144,
  "debug": 81
 }
} as const;
