// GENERATED by web-editor/scripts/generate-native-data.ts from web-editor/src/data/quizBank/quizSets.ts. Do not edit by hand.
/**
 * Quiz sets: a few related lessons practised together. The Quiz offers sets and the full quiz (there is no per-lesson quiz), so EVERY lesson
 * of a World belongs to exactly one set. A set quiz is every question of its lessons plus the set's own questions, which combine concepts
 * from more than one of those lessons (they carry `setId`).
 *
 * A set question's `lessonId` is the LAST lesson of its set: the point at which every concept it uses has been taught.
 *
 * The World's boss lesson is NOT in a set: it has its own entry (QuizBoss below), shown as a separate "Boss quiz" card, and the full quiz
 * (all the sets together) leaves it out.
 */
export interface QuizSet {
  id: string;
  /** Catalog id of the World (for example `world-1`). */
  worldId: string;
  title: string;
  /** One line shown on the set's card. */
  subtitle: string;
  /** Catalog lesson ids, in lesson order. */
  lessonIds: string[];
}

export const WORLD_1_QUIZ_SETS: QuizSet[] = [
  {
    id: 'w1-set-start',
    worldId: 'world-1',
    title: 'Getting Started',
    subtitle: 'What Kotlin is, how a program starts, comments and printing.',
    lessonIds: ['world-1-what-is-kotlin', 'world-1-kotlin-syntax', 'world-1-comments', 'world-1-print-println'],
  },
  {
    id: 'w1-set-variables',
    worldId: 'world-1',
    title: 'Variables',
    subtitle: 'val, var and how Kotlin picks a type.',
    lessonIds: ['world-1-val-vs-var', 'world-1-variables-type-inference'],
  },
  {
    id: 'w1-set-numbers-logic',
    worldId: 'world-1',
    title: 'Numbers & Logic',
    subtitle: 'Whole numbers, decimals and true/false results, mixed together.',
    lessonIds: ['world-1-int-long', 'world-1-float-double', 'world-1-boolean'],
  },
  {
    id: 'w1-set-text',
    worldId: 'world-1',
    title: 'Text',
    subtitle: 'Characters, Strings and templates, mixed together.',
    lessonIds: ['world-1-char', 'world-1-string', 'world-1-string-templates'],
  },
];

/** The final challenge of a World: questions that combine concepts from all of its lessons. */
export interface QuizBoss {
  id: string;
  worldId: string;
  title: string;
  subtitle: string;
  /** Catalog id of the World's boss lesson; its questions are the boss quiz. */
  lessonId: string;
}

export const WORLD_1_QUIZ_BOSS: QuizBoss = {
  id: 'w1-boss',
  worldId: 'world-1',
  title: 'Personal Profile Program',
  subtitle: 'Questions that combine everything in World 1.',
  lessonId: 'world-1-boss',
};
