/**
 * World 8 (Object Kingdom) practice-bank wording. Format: see world2.data.ts and PRACTICE_CONTENT_PASS.md.
 * Simple English: short everyday words, one idea per sentence. The code lives in world8.spec.ts.
 */
import type { WR, DBG } from './world2.data';

export const WR_DATA: Record<string, WR> = {
  'shelf-players': {
    summary: 'Write a class, make two objects, change one of them, and print both.',
    goal: 'Make a class for players. Create two players and give one of them a bonus. Print each player and the total score.',
    steps: [
      '**Write the class.** Above `main`, write `class Player` with two properties: `val name: String` and `var score: Int`.',
      '**Create two players.** Create `val ana` as `Player("Ana", 0)` and `val bo` as `Player("Bo", 5)`.',
      '**Give Ana the bonus.** Set `ana.score` to `ana.score` plus `bonus`.',
      '**Print three lines.** Join the text with `+`:\n"Ana: 10"\n"Bo: 5"\n"Total: 15"',
    ],
    i: ['**Write the class.** Put the properties in the class header.', '**Create two players.** Ana starts at `0`, Bo at `5`.', '**Give Ana the bonus.** Change her `score`.', '**Print three lines.** Include the total.'],
    e: ['**Write the class.**', '**Create two players.**', '**Give Ana the bonus.**', '**Print three lines.**'],
  },
  'roster-scan': {
    summary: 'Go through a list of objects to find the best mark, the average and the passes.',
    goal: 'A class has four students with marks. Find the best student, the average mark and how many students passed. Print three lines.',
    setup: 'The class `Student` and the list `students` are in the starter code.',
    steps: [
      '**Prepare the counters.** Create `var total = 0`, `var best = students[0]` and `var passed = 0`.',
      '**Check every student.** Loop over `students`. Add `s.mark` to `total`. When `s.mark` is bigger than `best.mark`, set `best` to `s`. When `s.mark` is at least `passMark`, add `1` to `passed`.',
      '**Print three lines.** The average is `total` divided by `students.size`. Int division drops the fraction:\n"Best: Cy (88)"\n"Average: 63"\n"Passed: 3 of 4"',
    ],
    i: ['**Prepare the counters.** Start `best` with the first student.', '**Check every student.** Update the total, the best student and the passes.', '**Print three lines.** Divide the total by the number of students.'],
    e: ['**Prepare the counters.**', '**Check every student.**', '**Print three lines.**'],
  },
  'visit-counter': {
    summary: 'Write an object that keeps one shared count, and use it from main.',
    goal: 'A website counts its visits in one place. Write an object that stores the count. Add some visits and print the result.',
    steps: [
      '**Write the object.** Above `main`, write `object VisitCounter`. Give it `var visits = 0`, a function `hit()` that adds `1` to `this.visits`, and a function `report()` that returns "Visits: " plus `this.visits`.',
      '**Count the visits.** Loop `hits` times. Each time, call `VisitCounter.hit()`.',
      '**Print the report.** Print `VisitCounter.report()`:\n"Visits: 3"',
      '**Add one more.** Call `hit()` once more, then print `VisitCounter.visits`:\n"4"',
    ],
    i: ['**Write the object.** Add `visits`, `hit()` and `report()`.', '**Count the visits.** Call `hit()` in a loop.', '**Print the report.**', '**Add one more.** Print `visits`.'],
    e: ['**Write the object.**', '**Count the visits.**', '**Print the report.**', '**Add one more.**'],
  },
  'shop-tax': {
    summary: 'Use a shared object inside a class method to work out a price with tax.',
    goal: 'A shop adds tax to every order. The tax rate and the order count are kept in one shared object. Price two orders and print the results and the order count.',
    setup: 'The object `Shop` and the class `Order` are in the starter code. `Order` still needs its `total()` method.',
    steps: [
      '**Write `total()`.** Inside `Order`, write `fun total(): Int`. It adds `1` to `Shop.orders`. It returns `this.amount` plus `this.amount * Shop.taxPercent / 100`.',
      '**Create two orders.** Create `val first` as `Order("Lamp", price)` and `val second` as `Order("Desk", 1200)`.',
      '**Print two prices.** Join the item and its total with `+`:\n"Lamp: 280"\n"Desk: 1320"',
      '**Print the order count.** Print `Shop.orders`:\n"Orders priced: 2"',
    ],
    i: ['**Write `total()`.** Count the order, then add the tax.', '**Create two orders.**', '**Print two prices.**', '**Print the order count.**'],
    e: ['**Write `total()`.**', '**Create two orders.**', '**Print two prices.**', '**Print the order count.**'],
  },
  'wallet': {
    summary: 'Change a var property of an object and print it.',
    goal: 'Mira has a wallet. Add her salary, take away some spending, and print how much is left and how much is spare.',
    setup: 'The class `Wallet` is in the starter code. `owner` is a `val` and `balance` is a `var`.',
    steps: [
      '**Add the salary.** Set `wallet.balance` to `wallet.balance` plus `salary`.',
      '**Spend some money.** Take `450` away from `wallet.balance` with `-=`.',
      '**Print the balance.** Join the owner and the balance with `+`:\n"Mira has 1050"',
      '**Print the spare money.** Create `val spare` as `wallet.balance` minus `500`, and print it:\n"Spare: 550"',
    ],
    i: ['**Add the salary.**', '**Spend some money.** Use `-=`.', '**Print the balance.**', '**Print the spare money.** Subtract `500`.'],
    e: ['**Add the salary.**', '**Spend some money.**', '**Print the balance.**', '**Print the spare money.**'],
  },
  'temperature-sensor': {
    summary: 'Add two computed properties with getters, and see them change with the value.',
    goal: 'A sensor stores a temperature in Celsius. Add two properties that are worked out from it: the Fahrenheit value and a "hot" flag. Print them, change the temperature, and print them again.',
    setup: 'The class `Sensor` is in the starter code. Write the two getters inside it.',
    steps: [
      '**Add `fahrenheit`.** Write `val fahrenheit: Int` with a getter. The getter returns `this.celsius * 9 / 5 + 32`.',
      '**Add `isHot`.** Write `val isHot: Boolean` with a getter. The getter is `true` when `this.celsius` is at least `30`.',
      '**Create the sensor.** Create `val sensor` as `Sensor("Roof", reading)`.',
      '**Print the first reading.** Join the label, `fahrenheit` and `isHot` with spaces:\n"Roof 77 false"',
      '**Change the temperature.** Set `sensor.celsius` to `reading + 10` and print the same line again:\n"Roof 95 true"',
    ],
    i: ['**Add `fahrenheit`.** Use a getter.', '**Add `isHot`.** Use a getter and `>=`.', '**Create the sensor.**', '**Print the first reading.**', '**Change the temperature.** Print again.'],
    e: ['**Add `fahrenheit`.**', '**Add `isHot`.**', '**Create the sensor.**', '**Print the first reading.**', '**Change the temperature.**'],
  },
  'rectangle-tools': {
    summary: 'Write three methods that return values, and call them on two objects.',
    goal: 'Give a rectangle class three methods: area, perimeter and a check for a square. Use them on two rectangles and print the results.',
    setup: 'The class `Rectangle` is in the starter code with `width` and `height`.',
    steps: [
      '**Write `area()`.** It returns `this.width * this.height`.',
      '**Write `perimeter()`.** It returns `2 * (this.width + this.height)`.',
      '**Write `isSquare()`.** It returns `true` when `this.width` equals `this.height`. Give it the return type `Boolean`.',
      '**Create two rectangles.** Create `val a` as `Rectangle(side, 4)` and `val b` as `Rectangle(side, side)`.',
      '**Print two lines.** Join the label and the three answers with spaces:\n"A: 24 20 false"\n"B: 36 24 true"',
    ],
    i: ['**Write `area()`.**', '**Write `perimeter()`.**', '**Write `isSquare()`.** Return a `Boolean`.', '**Create two rectangles.**', '**Print two lines.**'],
    e: ['**Write `area()`.**', '**Write `perimeter()`.**', '**Write `isSquare()`.**', '**Create two rectangles.**', '**Print two lines.**'],
  },
  'account-ops': {
    summary: 'Write a method that can say no, and count how often it does.',
    goal: 'A bank account can take money in and pay money out. A payment must fail when there is not enough money. Make some payments, count the failures, and print the balance.',
    setup: 'The class `Account` is in the starter code with `deposit()`. Write `withdraw()` inside it.',
    steps: [
      '**Write `withdraw()`.** It takes `amount: Int` and returns a `Boolean`. When `amount` is bigger than `this.balance`, return `false`. If not, take the amount from `this.balance` and return `true`.',
      '**Deposit money.** Call `account.deposit(50)`.',
      '**Try three payments.** Call `account.withdraw` with `120`, then `100`, then `30`. Each time it returns `false`, add `1` to `failed`.',
      '**Print two lines.** Print the balance and the failures:\n"Balance: 0"\n"Failed: 1"',
    ],
    i: ['**Write `withdraw()`.** Return `false` when the money is not enough.', '**Deposit money.**', '**Try three payments.** Count the failures.', '**Print two lines.**'],
    e: ['**Write `withdraw()`.**', '**Deposit money.**', '**Try three payments.**', '**Print two lines.**'],
  },
  'price-tag': {
    summary: 'Use constructor parameters and an init block to work out a property.',
    goal: 'A price tag is made from a base price and a tax percent. Work out the total price when the object is created. Make two tags and print their totals.',
    setup: 'The class header `Price(base, taxPercent)` is in the starter code. Its parameters are not properties.',
    steps: [
      '**Declare the property.** Inside `Price`, write `val total: Int`.',
      '**Fill it in `init`.** In an `init` block, set `this.total` to `base + base * taxPercent / 100`. Int division drops the fraction.',
      '**Create two tags.** Create `val shirt` as `Price(base, 10)` and `val shoes` as `Price(120, 25)`.',
      '**Print two lines.** Join the label and the total with `+`:\n"Shirt: 93"\n"Shoes: 150"',
    ],
    i: ['**Declare the property.**', '**Fill it in `init`.** Use the constructor parameters.', '**Create two tags.**', '**Print two lines.**'],
    e: ['**Declare the property.**', '**Fill it in `init`.**', '**Create two tags.**', '**Print two lines.**'],
  },
  'member-card': {
    summary: 'Write a class with default values and create objects in three different ways.',
    goal: 'A shop has member cards. Most members only need a name. Make a class where the level and the points have default values. Create three members in different ways and print them.',
    steps: [
      '**Write the class.** Above `main`, write `class Member` with `val name: String`, `val level: String = "Basic"` and `var points: Int = 0` in the class header.',
      '**Create three members.** Create `val a` as `Member("Ana")`. Create `val b` as `Member("Bo", "Gold", 150)`. Create `val c` as `Member(name = "Cy", points = 40)`.',
      '**Add the welcome points.** Set `a.points` to `a.points` plus `welcome`.',
      '**Print three lines.** Join the name, level and points with spaces:\n"Ana Basic 20"\n"Bo Gold 150"\n"Cy Basic 40"',
    ],
    i: ['**Write the class.** Use default values.', '**Create three members.** Use defaults, positions and names.', '**Add the welcome points.**', '**Print three lines.**'],
    e: ['**Write the class.**', '**Create three members.**', '**Add the welcome points.**', '**Print three lines.**'],
  },
  'creation-log': {
    summary: 'Use an init block to print a message and count every object that is created.',
    goal: 'Every time a ticket is created, print a message and count it in a shared place. Create two tickets, then print the count and the ticket labels.',
    setup: 'The object `Registry` and the class `Ticket` are in the starter code. `Ticket` still needs its `init` block.',
    steps: [
      '**Write the `init` block.** Inside `Ticket`, write an `init` block. It prints "Creating " plus `label`, then adds `1` to `Registry.count`.',
      '**Create two tickets.** Create `val a` as `Ticket(first)` and `val b` as `Ticket(first + 1)`.',
      '**Print the count.** Print `Registry.count`:\n"Created: 2"',
      '**Print the labels.** Print the two labels with a comma between them:\n"Seat 12, Seat 13"',
    ],
    i: ['**Write the `init` block.** Print, then count.', '**Create two tickets.**', '**Print the count.**', '**Print the labels.**'],
    e: ['**Write the `init` block.**', '**Create two tickets.**', '**Print the count.**', '**Print the labels.**'],
  },
  'safe-box': {
    summary: 'Keep a code private and let other code use it only through a method.',
    goal: 'A safe box hides its secret code. Other code may only guess the code by calling a method. Count the guesses. Make two guesses and print the results.',
    setup: 'The class header `SafeBox(private val code: Int, val label: String)` is in the starter code.',
    steps: [
      '**Add a private counter.** Write `private var attempts = 0`.',
      '**Write `open()`.** It takes `guess: Int` and returns a `Boolean`. It adds `1` to `this.attempts`, then returns `true` when `guess` equals `this.code`.',
      '**Write `attemptsUsed()`.** It returns `this.attempts`.',
      '**Create the box and guess.** Create `val box` as `SafeBox(secret, "Vault")`. Print the label and the result of `box.open(1234)`:\n"Vault opened: false"',
      '**Guess again and count.** Print the same line for `box.open(secret)`, then print the attempts:\n"Vault opened: true"\n"Attempts: 2"',
    ],
    i: ['**Add a private counter.**', '**Write `open()`.** Count, then compare.', '**Write `attemptsUsed()`.**', '**Create the box and guess.**', '**Guess again and count.**'],
    e: ['**Add a private counter.**', '**Write `open()`.**', '**Write `attemptsUsed()`.**', '**Create the box and guess.**', '**Guess again and count.**'],
  },
  'ledger-privacy': {
    summary: 'Use a private property and a private setter, and read them through methods.',
    goal: 'A ledger keeps a hidden total. Other code can read the number of entries but cannot change it. Record three amounts, then print a summary and the number of entries.',
    setup: 'The class `Ledger` is in the starter code with `total` (private) and `entries` (public to read, private to change).',
    steps: [
      '**Write `record()`.** It takes `amount: Int`. It adds `amount` to `this.total` and adds `1` to `this.entries`.',
      '**Write `summary()`.** It returns "Entries: ", `this.entries`, ", total: " and `this.total`, joined with `+`.',
      '**Create the ledger.** Create `val ledger` as `Ledger()`.',
      '**Record three amounts.** Call `record` with `100`, then `250`, then `bonus`.',
      '**Print two lines.** Print the summary and the entries:\n"Entries: 3, total: 390"\n"3"',
    ],
    i: ['**Write `record()`.** Update both properties.', '**Write `summary()`.**', '**Create the ledger.**', '**Record three amounts.**', '**Print two lines.**'],
    e: ['**Write `record()`.**', '**Write `summary()`.**', '**Create the ledger.**', '**Record three amounts.**', '**Print two lines.**'],
  },
  'product-compare': {
    summary: 'Write a data class, then compare objects by value and make a changed copy.',
    goal: 'A shop has products with a name and a price. Compare two equal products, make a cheaper copy, and print the results.',
    steps: [
      '**Write the data class.** Above `main`, write `data class Product` with `val name: String` and `val price: Int`.',
      '**Create two products.** Create `val a` and `val b`. Both are `Product("Pen", 20)`.',
      '**Make a sale copy.** Create `val sale` as `a.copy(price = a.price - discount)`.',
      '**Print four lines.** Print `a`, then `a == b`, then `a == sale`, then `sale`:\n"Product(name=Pen, price=20)"\n"true"\n"false"\n"Product(name=Pen, price=15)"',
    ],
    i: ['**Write the data class.**', '**Create two products.** Use the same values.', '**Make a sale copy.** Use `copy`.', '**Print four lines.**'],
    e: ['**Write the data class.**', '**Create two products.**', '**Make a sale copy.**', '**Print four lines.**'],
  },
  'order-lines': {
    summary: 'Go through data class objects, take them apart, and make a changed copy.',
    goal: 'An order has three lines. Print each line total, then the subtotal with tax, the most expensive item and a copy of that item with double the amount.',
    setup: 'The data class `Line` is in the starter code.',
    steps: [
      '**Prepare the trackers.** Create `var subtotal = 0` and `var priciest = lines[0]`.',
      '**Go through the lines.** Loop over `lines`. Take each line apart with `val (item, qty, unit) = line`. Print the item, the quantity and `qty * unit`. Add `qty * unit` to `subtotal`. When `unit` is bigger than `priciest.unit`, set `priciest` to `line`.\n"Pen x3 = 12"\n"Book x2 = 30"\n"Bag x1 = 40"',
      '**Work out the tax.** Create `val tax` as `subtotal * taxPercent / 100`. Print the subtotal and the tax. Int division drops the fraction:\n"Subtotal: 82, tax: 8"',
      '**Print the priciest item.** Print its `item`:\n"Priciest: Bag"',
      '**Print a doubled copy.** Print `priciest.copy(qty = priciest.qty * 2)`:\n"Line(item=Bag, qty=2, unit=40)"',
    ],
    i: ['**Prepare the trackers.**', '**Go through the lines.** Take each line apart.', '**Work out the tax.** Use Int division.', '**Print the priciest item.**', '**Print a doubled copy.** Use `copy`.'],
    e: ['**Prepare the trackers.**', '**Go through the lines.**', '**Work out the tax.**', '**Print the priciest item.**', '**Print a doubled copy.**'],
  },
  'traffic-cycle': {
    summary: 'Write an enum with a property, loop over its constants and add up a value.',
    goal: 'A traffic light has three colors, and each one lasts some seconds. Print each color with its number, add up the cycle time, and find the time for several rounds.',
    steps: [
      '**Write the enum.** Above `main`, write `enum class Signal(val seconds: Int)` with three constants: `RED(30)`, `GREEN(25)` and `YELLOW(5)`.',
      '**Print every color.** Loop over `Signal.values()`. Print the number (`s.ordinal + 1`), the name and the seconds, and add `s.seconds` to `cycle`. Use a string template:\n"1. RED 30s"\n"2. GREEN 25s"\n"3. YELLOW 5s"',
      '**Print the cycle.** Print `cycle` with the text "Cycle: " before it and "s" after it:\n"Cycle: 60s"',
      '**Print the time for all rounds.** Multiply `cycle` by `rounds`:\n"After 3 rounds: 180s"',
    ],
    i: ['**Write the enum.** Give each constant its seconds.', '**Print every color.** Use `values()` and `ordinal`.', '**Print the cycle.**', '**Print the time for all rounds.**'],
    e: ['**Write the enum.**', '**Print every color.**', '**Print the cycle.**', '**Print the time for all rounds.**'],
  },
  'size-menu': {
    summary: 'Use an enum in a list, with a function that picks a letter for each size.',
    goal: 'A coffee shop sells three sizes. For an order of four cups, find the size letters, the total cost with an extra shot, the total volume and the number of small cups.',
    setup: 'The enum `Size` is in the starter code.',
    steps: [
      '**Write `label()`.** Above `main`, write `fun label(size: Size): String`. Use `when` to return "S" for `SMALL`, "M" for `MEDIUM` and "L" for `LARGE`.',
      '**Go through the order.** Loop over `order`. For each `size`, add `size.price + extraShot` to `cost` and `size.ml` to `volume`. Add `label(size)` to `codes`. When `size` is `Size.SMALL`, add `1` to `smalls`.',
      '**Print three lines.** Join the text with `+`:\n"Order: SLSM"\n"Cost: 20, volume: 1350ml"\n"Smalls: 2"',
    ],
    i: ['**Write `label()`.** Use `when` on the enum.', '**Go through the order.** Update all four counters.', '**Print three lines.**'],
    e: ['**Write `label()`.**', '**Go through the order.**', '**Print three lines.**'],
  },
  'vehicle-fleet': {
    summary: 'Write two subclasses of an open class, and call a method from the parent.',
    goal: 'A fleet has vehicles. A bike and a truck both extend a general vehicle class. The truck also carries a load. Print a description of each and the total number of wheels.',
    setup: 'The open class `Vehicle` is in the starter code.',
    steps: [
      '**Write `Bike`.** Write `class Bike(name: String)` that extends `Vehicle`. Pass `name` and `2` wheels to `Vehicle`.',
      '**Write `Truck`.** Write `class Truck(name: String, val load: Int)` that extends `Vehicle`. Pass `name` and `6` wheels. Override `describe()`: return `super.describe()` plus " and carries ", `this.load` and "kg".',
      '**Create two vehicles.** Create `val bike` as `Bike("Swift")` and `val truck` as `Truck("Hauler", capacity)`.',
      '**Print two descriptions.** Print `bike.describe()` and `truck.describe()`:\n"Swift has 2 wheels"\n"Hauler has 6 wheels and carries 800kg"',
      '**Print the wheels.** Add `bike.wheels` and `truck.wheels`:\n"Wheels: 8"',
    ],
    i: ['**Write `Bike`.** Extend `Vehicle`.', '**Write `Truck`.** Extend `Vehicle` and override `describe()`.', '**Create two vehicles.**', '**Print two descriptions.**', '**Print the wheels.**'],
    e: ['**Write `Bike`.**', '**Write `Truck`.**', '**Create two vehicles.**', '**Print two descriptions.**', '**Print the wheels.**'],
  },
  'payroll': {
    summary: 'Override a method in two subclasses and add up the pay of a mixed list.',
    goal: 'A company has employees, managers and interns. A manager gets a bonus and an intern gets half pay. Print the pay of each person and the total payroll.',
    setup: 'The open class `Employee` is in the starter code.',
    steps: [
      '**Write `Manager`.** Write `class Manager(name: String, base: Int, val bonus: Int)` that extends `Employee`. Override `pay()`: return `super.pay()` plus `this.bonus`.',
      '**Write `Intern`.** Write `class Intern(name: String)` that extends `Employee`. Pass `name` and a base of `505`. Override `pay()`: return `super.pay() / 2`.',
      '**Make the staff list.** Create `val staff: List<Employee>` with `Employee("Ana", 2000)`, `Manager("Bo", 3000, bonus)` and `Intern("Cy")`. Also create `var payroll = 0`.',
      '**Print every pay.** Loop over `staff`. Print the name and `e.pay()`, and add `e.pay()` to `payroll`:\n"Ana: 2000"\n"Bo: 3800"\n"Cy: 252"',
      '**Print the payroll.**\n"Payroll: 6052"',
    ],
    i: ['**Write `Manager`.** Add the bonus to the base pay.', '**Write `Intern`.** Halve the base pay.', '**Make the staff list.**', '**Print every pay.** Add up the payroll.', '**Print the payroll.**'],
    e: ['**Write `Manager`.**', '**Write `Intern`.**', '**Make the staff list.**', '**Print every pay.**', '**Print the payroll.**'],
  },
  'shape-areas': {
    summary: 'Write two classes that implement one interface, and use them in a list.',
    goal: 'Two kinds of shapes both know their area and their label. Make a list with one of each, print each shape, and print the total area.',
    setup: 'The interface `Shape` is in the starter code.',
    steps: [
      '**Write `Square`.** Write `class Square(val side: Int)` that implements `Shape`. `area()` returns `this.side * this.side`. `label()` returns "Square " plus `this.side`.',
      '**Write `Rect`.** Write `class Rect(val w: Int, val h: Int)` that implements `Shape`. `area()` returns `this.w * this.h`. `label()` returns "Rect ", `this.w`, "x" and `this.h`, joined with `+`.',
      '**Make the list.** Create `val shapes: List<Shape>` with `Square(side)` and `Rect(4, 3)`. Also create `var total = 0`.',
      '**Print the shapes.** Loop over `shapes`. Print the label, " = " and the area, and add the area to `total`. Then print the total:\n"Square 5 = 25"\n"Rect 4x3 = 12"\n"Total area: 37"',
    ],
    i: ['**Write `Square`.** Implement both functions.', '**Write `Rect`.** Implement both functions.', '**Make the list.**', '**Print the shapes.** Add up the total.'],
    e: ['**Write `Square`.**', '**Write `Rect`.**', '**Make the list.**', '**Print the shapes.**'],
  },
  'notifier-channels': {
    summary: 'Write two classes for one interface and send one message through both.',
    goal: 'An app can send a message by email or by SMS. An SMS keeps only the first ten characters. Send one message through both channels and print how many characters were sent in total.',
    setup: 'The interface `Notifier` and the function `broadcast` are in the starter code. `broadcast` prints each line and returns the number of characters.',
    steps: [
      '**Write `Email`.** Write `class Email(val address: String)` that implements `Notifier`. `send(message)` returns "EMAIL to ", `this.address`, ": " and `message`, joined with `+`.',
      '**Write `Sms`.** Write `class Sms(val number: String)` that implements `Notifier`. `send(message)` returns "SMS to ", `this.number`, ": " and `message.take(10)`, joined with `+`.',
      '**Send the message.** Create `val sent` as `broadcast(listOf(Email("ops@x.org"), Sms("555-0101")), text)`. It prints two lines:\n"EMAIL to ops@x.org: Server restarts at noon"\n"SMS to 555-0101: Server res"',
      '**Print the total.** Print `sent`:\n"Characters sent: 70"',
    ],
    i: ['**Write `Email`.** Implement `send`.', '**Write `Sms`.** Keep only ten characters of the message.', '**Send the message.** Use `broadcast`.', '**Print the total.**'],
    e: ['**Write `Email`.**', '**Write `Sms`.**', '**Send the message.**', '**Print the total.**'],
  },
  'animal-sounds': {
    summary: 'Override a property and a method, and keep the parent values where you do not.',
    goal: 'Animals have four legs and a sound. A bird has its own number of legs and sound. A cat has its own sound. Print each animal and the total number of legs.',
    setup: 'The open class `Animal` is in the starter code.',
    steps: [
      '**Write `Bird`.** Write `class Bird(override val legs: Int)` that extends `Animal`. Override `sound()` to return "Tweet".',
      '**Write `Cat`.** Write `class Cat` that extends `Animal`. Override `sound()` to return "Meow". Keep the legs from `Animal`.',
      '**Make the zoo.** Create `val zoo: List<Animal>` with `Animal()`, `Bird(birdLegs)` and `Cat()`. Also create `var legs = 0`.',
      '**Print every animal.** Loop over `zoo`. Print the sound and the legs, and add the legs to `legs`. Then print the total:\n"... 4"\n"Tweet 2"\n"Meow 4"\n"Total legs: 10"',
    ],
    i: ['**Write `Bird`.** Override the legs and the sound.', '**Write `Cat`.** Override only the sound.', '**Make the zoo.**', '**Print every animal.** Add up the legs.'],
    e: ['**Write `Bird`.**', '**Write `Cat`.**', '**Make the zoo.**', '**Print every animal.**'],
  },
  'discount-policy': {
    summary: 'Override a method with a parameter in two subclasses and compare the prices.',
    goal: 'A shop has three offers: no discount, a percent off and a flat amount off. Work out the price for each offer and print the cheapest one.',
    setup: 'The open class `Discount` is in the starter code.',
    steps: [
      '**Write `Percent`.** Write `class Percent(label: String, val percent: Int)` that extends `Discount`. Override `apply(price)`: return `price - price * this.percent / 100`. Int division drops the fraction.',
      '**Write `Flat`.** Write `class Flat(label: String, val amount: Int)` that extends `Discount`. Override `apply(price)`: return `price - this.amount`.',
      '**Make the offers.** Create `val offers: List<Discount>` with `Discount("None")`, `Percent("Spring", 15)` and `Flat("Coupon", 40)`. Also create `var cheapest` and start it at `basePrice`.',
      '**Price every offer.** Loop over `offers`. Create `val result` as `offer.apply(basePrice)`. Print the label and `result`. When `result` is smaller than `cheapest`, set `cheapest` to `result`:\n"None: 250"\n"Spring: 213"\n"Coupon: 210"',
      '**Print the cheapest price.** After the loop:\n"Cheapest: 210"',
    ],
    i: ['**Write `Percent`.** Take a percent off.', '**Write `Flat`.** Take a fixed amount off.', '**Make the offers.** Start `cheapest` at the base price.', '**Price every offer.** Keep the cheapest.', '**Print the cheapest price.**'],
    e: ['**Write `Percent`.**', '**Write `Flat`.**', '**Make the offers.**', '**Price every offer.**', '**Print the cheapest price.**'],
  },
};

export const DBG_SUMMARY: Record<string, string> = {
  'shared-score': 'Two names for one object make both counters change.',
  'scattered-total': 'A new object is made on every call, so the total is lost.',
  'frozen-balance': 'A val property cannot be changed, so the program does not compile.',
  'fence-length': 'A method adds two sides and forgets the other two.',
  'pack-weight': 'The init block adds the numbers where it should multiply them.',
  'hidden-title': 'A constructor parameter without val is not a property.',
  'visitor-count': 'The counter is inside each object, so it always shows 1.',
  'peek-locker': 'A private property cannot be read from outside the class.',
  'unequal-points': 'A plain class does not compare objects by value.',
  'plan-seats': 'The ordinal is the position, not the seat count.',
  'pet-without-name': 'The parent class constructor is called without its argument.',
  'missing-currency': 'The class does not implement every member of its interface.',
  'closed-speak': 'A member that is not open cannot be overridden.',
};

export const DBG_DATA: Record<string, DBG> = {
  'shared-score': {
    subtitle: 'Only `second` should change, so the program should print "First: 0" and "Second: 5", but it prints "First: 5" and "Second: 5".',
    hints: ['Both lines show 5, but the code adds 5 only once. How many counters does the program really have?', '`val second = first` does not make a new counter. It gives the same counter a second name. What happens when one name changes it?', 'Make `second` a counter of its own.'],
    explanation: '`val second = first` copies the reference, not the object, so `first` and `second` are two names for ONE `Counter`. Adding 5 through `second` changes what `first` shows too. `Counter(0)` creates a separate object, so only `second` changes.',
  },
  'scattered-total': {
    subtitle: 'The program should print "Total: 30", but it prints "Total: 0".',
    hints: ['Both numbers are added, but the total is `0`. Where does each number go?', 'Every `Stats()` call creates a NEW object with its own total of `0`. What do you need so that all calls share one total?', 'Use a declaration that makes exactly one shared instance, and call it by its name.'],
    explanation: 'A `class` makes a new object each time you call `Stats()`, so `10` and `20` were added to two objects that were thrown away, and a third new object was printed. An `object` is created once, so every `Stats.add(...)` and `Stats.total` use the same total.',
  },
  'frozen-balance': {
    subtitle: 'The program should print "Mia: 150", but it does not compile.',
    hints: ['The error is on the line that adds `50`. What is that line trying to do to `balance`?', 'The line changes `balance`. How is `balance` declared in the class?', 'Make the property a kind that can change after it is created.'],
    explanation: 'A `val` property is set once and can never be assigned again, so `acc.balance += 50` is a compile error. A `var` property can change. With `var balance`, the balance becomes 150.',
  },
  'fence-length': {
    subtitle: 'The fence of a 12 by 8 garden should be 40, so the program should print "Fence: 40", but it prints "Fence: 20".',
    hints: ['The result is exactly half of what it should be. How many sides does a garden have?', 'The method adds the length and the width once. A fence goes round the whole garden. How many lengths and widths are there?', 'Count both pairs of sides in the formula.'],
    explanation: 'A fence goes all the way round, so it has two lengths and two widths. `this.length + this.width` counts only half of them. `2 * (this.length + this.width)` counts all four sides: 2 * (12 + 8) = 40.',
  },
  'pack-weight': {
    subtitle: 'Six items of 4 kg each should weigh 24, so the program should print "Weight: 24", but it prints "Weight: 10".',
    hints: ['The result is far too small. Look at how `init` combines the two numbers.', '`items + weightEach` adds 6 and 4. What do you really want: the sum of two numbers, or a total weight of several equal items?', 'Use the operation that repeats a number several times.'],
    explanation: 'The total weight of 6 items of 4 kg each is `6 * 4 = 24`. The `init` block used `+`, which gave `6 + 4 = 10`. Changing it to `items * weightEach` fixes the total.',
  },
  'hidden-title': {
    subtitle: 'The program should print "Horizon: 3", but it does not compile.',
    hints: ['The error is about `title` on the line that prints. Compare how `title` and `plays` are written in the class header.', '`plays` has `val`, but `title` does not. What is a constructor parameter without `val` or `var`?', 'Make `title` a property, like `plays`.'],
    explanation: 'A constructor parameter without `val` or `var` is only a value you can use while the object is built, not a property. So `song.title` does not exist. Writing `val title: String` makes it a property you can read.',
  },
  'visitor-count': {
    subtitle: 'The visitors should be numbered 1, 2 and 3, so the program should print "Visitor #1: Ana", "Visitor #2: Bo" and "Visitor #3: Cy", but every line says "#1".',
    hints: ['Every visitor gets the number `1`. Where does the number come from?', '`var count = 0` is inside `Visitor`, so each new visitor gets its own `count` that starts at `0`. Who should keep the count for all visitors?', 'Keep the count in one place that is shared by all visitors.'],
    explanation: 'A property of a class belongs to each object, so each new `Visitor` starts with its own `count` of `0` and adds `1`. To count all visitors together, keep the number in an `object`, such as `Tally`, which exists only once.',
  },
  'peek-locker': {
    subtitle: 'The program should print "Open" and then "Locked", but it does not compile.',
    hints: ['The error is on the last `println`. Which property does it read?', '`code` is declared `private`. Who is allowed to read a private property?', 'Do not read the code directly. Ask the object a question through a method that is open to everyone.'],
    explanation: 'A `private` property can only be used inside its own class, so `locker.code` is a compile error outside it. The class already has a public method for this job: `unlock(guess)` tells you if a guess is right without showing the code.',
  },
  'unequal-points': {
    subtitle: 'The two points are the same, so the program should print "true" and "Point(x=2, y=3)", but it prints "false" and something unreadable.',
    hints: ['Both points hold `2` and `3`, yet they are not equal, and printing one does not show its values. What do both lines have in common?', 'A plain class compares objects by identity and prints a default text. Which kind of class compares by value and prints its properties?', 'Change the kind of class, not the main function.'],
    explanation: 'A plain `class` treats two objects as equal only when they are the very same object, and its default text is not readable. A `data class` generates `equals` that compares the properties, and a `toString` that shows them: `Point(x=2, y=3)`.',
  },
  'plan-seats': {
    subtitle: 'The team plan should show its seats, so the program should print "TEAM seats: 5", but it prints "TEAM seats: 1".',
    hints: ['The number is `1`, but the plan has `5` seats. Which property does the last line read?', '`ordinal` is the position of the constant in the list, starting at `0`. `TEAM` is second, so its position is `1`. Where is the real seat count stored?', 'Read the property that you gave to each constant.'],
    explanation: '`plan.ordinal` is the position of the constant in the enum (`FREE` is 0, `TEAM` is 1). The seat count is the property `seats`, which you set for each constant. `plan.seats` gives 5.',
  },
  'pet-without-name': {
    subtitle: 'The program should print "I am Rex", but it does not compile.',
    hints: ['The error is on the line with `class Dog`. Look at what is written after the colon.', '`Pet` needs a `name` when it is built, but `Pet()` passes nothing. What does `Dog` have that it could pass on?', 'Hand the dog\'s name to the parent class.'],
    explanation: 'A subclass must call the constructor of its parent class with all the arguments it needs. `Pet(val name: String)` needs a name, so `Pet()` is a compile error. `Dog(name: String) : Pet(name)` passes the name on.',
  },
  'missing-currency': {
    subtitle: 'The invoice should print "90 EUR", but the program does not compile.',
    hints: ['The error names a member of the interface. Compare the interface with the class.', '`Payable` has two functions, `amount()` and `currency()`. How many does `Invoice` implement?', 'Add the member that is missing, with the same name and return type.'],
    explanation: 'A class that implements an interface must implement every member of it. `Invoice` has `amount()` but not `currency()`, so it does not compile. Adding `override fun currency() = "EUR"` completes it.',
  },
  'closed-speak': {
    subtitle: 'A duck should say "Quack", so the program should print "Quack", but it does not compile.',
    hints: ['The error says the member cannot be overridden. Look at the function in the parent class.', 'In Kotlin, members are closed by default. `Bird.speak()` has no `open`. What does `Duck` try to do with it?', 'Allow the parent function to be overridden.'],
    explanation: 'In Kotlin a member can only be overridden when the parent marks it `open`. `fun speak()` in `Bird` is final, so `override fun speak()` in `Duck` is an error. Writing `open fun speak()` in `Bird` allows it.',
  },
};
